export interface FAQItem {
  cat: string
  d: string   // domanda
  r: string   // risposta
}

export const faqs: FAQItem[] = [
  // ── Consultazioni ────────────────────────────────────────────────────────────
  { cat: 'Consultazioni', d: "Come posso fissare un appuntamento con l'Avv. Cuomo?", r: "Puoi fissare un appuntamento chiamando lo studio al +39 081 9211148 o al cellulare +39 333 8001857, inviando una email a cuomo.avv.giuseppe@tiscali.it, oppure utilizzando il modulo di contatto sul sito. Sono disponibili anche consulenze online tramite Zoom, Teams o Google Meet." },
  { cat: 'Consultazioni', d: "È possibile una prima consulenza online o da remoto?", r: "Sì. Lo studio offre consulenze online su appuntamento tramite Zoom, Microsoft Teams e Google Meet. Questo servizio è particolarmente utile per chi non può raggiungere fisicamente la sede di Nocera Inferiore o per un primo orientamento." },
  { cat: 'Consultazioni', d: "Cosa devo portare al primo appuntamento?", r: "È utile portare tutta la documentazione relativa al caso (contratti, comunicazioni scritte, atti ricevuti, sentenze, cartelle cliniche ecc.). Non preoccuparti se non hai tutto: l'avvocato indicherà durante il colloquio quali documenti sono necessari per la valutazione completa." },
  { cat: 'Consultazioni', d: "Lo studio riceve anche fuori dai normali orari d'ufficio?", r: "Per urgenze, l'Avv. Cuomo è raggiungibile al cellulare +39 333 8001857 anche fuori orario. Per appuntamenti ordinari, lo studio è aperto dal lunedì al venerdì. Si consiglia di chiamare preventivamente per concordare l'orario." },
  { cat: 'Consultazioni', d: "Posso inviare documenti per email prima della consulenza?", r: "Sì, è possibile inviare documenti in anticipo all'indirizzo cuomo.avv.giuseppe@tiscali.it per permettere all'avvocato di prepararsi meglio. Si consiglia di allegare file in formato PDF e di descrivere sinteticamente il caso." },

  // ── Diritto di Famiglia ───────────────────────────────────────────────────────
  { cat: 'Diritto di Famiglia', d: "Qual è la differenza tra separazione consensuale e giudiziale?", r: "La separazione consensuale avviene quando i coniugi raggiungono un accordo su tutte le condizioni (figli, assegno, casa). È più rapida e meno costosa. La separazione giudiziale si ha quando i coniugi non trovano un accordo e il giudice decide sulle condizioni contestate. Quest'ultima ha tempi più lunghi e costi maggiori." },
  { cat: 'Diritto di Famiglia', d: "Quanto dura il divorzio breve?", r: "Con la Legge 55/2015 i tempi di separazione prima del divorzio si sono ridotti: 6 mesi per la separazione consensuale e 12 mesi per quella giudiziale. Dopo questi periodi si può chiedere il divorzio. Con accordo tra le parti, il divorzio consensuale richiede generalmente altri 3-12 mesi." },
  { cat: 'Diritto di Famiglia', d: "Con la negoziazione assistita è necessario andare in tribunale?", r: "No. La negoziazione assistita per separazione e divorzio (senza figli minori o incapaci) si conclude con un accordo tra avvocati trasmesso alla Procura della Repubblica per il nulla osta. Non è richiesta alcuna udienza, il che riduce notevolmente i tempi." },
  { cat: 'Diritto di Famiglia', d: "Come viene calcolato l'assegno di mantenimento per i figli?", r: "L'assegno per i figli si determina tenendo conto delle esigenze del minore, del tenore di vita durante il matrimonio, dei tempi di permanenza con ciascun genitore e delle capacità economiche di entrambi i genitori. Non esiste una formula fissa: ogni caso è valutato individualmente dal giudice." },
  { cat: 'Diritto di Famiglia', d: "Posso chiedere la revisione dell'assegno di mantenimento?", r: "Sì. L'assegno può essere rivisto in caso di mutamento delle circostanze: perdita del lavoro, nuovo lavoro, matrimonio dell'ex coniuge, crescita dei figli, cambio di residenza. È necessario presentare un ricorso al Tribunale dimostrando il cambiamento significativo della situazione." },
  { cat: 'Diritto di Famiglia', d: "Cosa succede ai figli in caso di separazione?", r: "In linea di principio, il giudice dispone l'affidamento condiviso dei figli a entrambi i genitori, con collocamento prevalente presso uno di essi. L'affidamento esclusivo è disposto solo in casi eccezionali di pregiudizio per il minore. Il giudice tiene sempre conto dell'interesse superiore del minore." },
  { cat: 'Diritto di Famiglia', d: "L'assegno divorzile è sempre dovuto?", r: "No. La Cassazione (sent. n. 11504/2017) ha chiarito che l'assegno divorzile spetta solo al coniuge che non abbia redditi adeguati per mantenersi, con valutazione dell'autosufficienza economica del richiedente. La valutazione è complessiva e tiene conto anche del contributo dato durante il matrimonio." },

  // ── Diritto del Lavoro ────────────────────────────────────────────────────────
  { cat: 'Diritto del Lavoro', d: "Entro quando devo contestare un licenziamento?", r: "Il termine è tassativo: entro 60 giorni dalla ricezione del licenziamento scritto bisogna presentare impugnazione stragiudiziale (raccomandata o PEC). Dopodiché, entro 180 giorni dall'impugnazione, va depositato il ricorso in tribunale. Il mancato rispetto comporta la decadenza dal diritto." },
  { cat: 'Diritto del Lavoro', d: "Cosa prevede il Jobs Act in caso di licenziamento illegittimo?", r: "Per i contratti a tutele crescenti stipulati dopo il 7 marzo 2015, il reintegro è previsto solo per licenziamenti discriminatori, nulli o per specifici vizi formali gravi. Negli altri casi è prevista un'indennità risarcitoria da 2 a 12 mensilità." },
  { cat: 'Diritto del Lavoro', d: "Ho subito mobbing: come lo dimostro?", r: "Il mobbing richiede la prova di una condotta sistematica e reiterata nel tempo, finalizzata ad emarginare il lavoratore. È fondamentale conservare email, messaggi, comunicazioni scritte, registrare date e modalità degli episodi, raccogliere testimonianze di colleghi e ottenere certificazioni mediche." },
  { cat: 'Diritto del Lavoro', d: "Posso lavorare senza contratto scritto e avere diritti?", r: "Sì. Il contratto di lavoro non deve necessariamente essere scritto: anche il lavoro di fatto è giuridicamente tutelato. Il lavoratore in nero può agire in giudizio per far riconoscere il rapporto di lavoro e ottenere la regolarizzazione previdenziale, il pagamento delle retribuzioni arretrate, il TFR e le ferie non godute." },
  { cat: 'Diritto del Lavoro', d: "Quando scattano le tutele dell'infortunio sul lavoro?", r: "L'INAIL copre gli infortuni durante lo svolgimento dell'attività lavorativa, incluso il percorso casa-lavoro (infortunio in itinere). Se l'infortunio è causato anche dalla colpa del datore, il lavoratore può agire in sede civile per il danno differenziale non coperto dall'INAIL." },
  { cat: 'Diritto del Lavoro', d: "Quanto tempo ho per rivendicare crediti di lavoro?", r: "Il termine di prescrizione ordinario per i crediti di lavoro è di 5 anni dalla cessazione del rapporto. Alcune voci si prescrivono in termini diversi. Il TFR si prescrive in 5 anni. Per i lavoratori autonomi i crediti si prescrivono in 3 anni." },

  // ── Diritto Civile ────────────────────────────────────────────────────────────
  { cat: 'Diritto Civile', d: "Cos'è un decreto ingiuntivo e come posso oppormi?", r: "Il decreto ingiuntivo è un provvedimento con cui il Tribunale ordina al debitore di pagare un credito documentato. Se si riceve un decreto ingiuntivo, si hanno 40 giorni dalla notifica per presentare opposizione con atto di citazione. Decorso inutilmente questo termine, il decreto diventa esecutivo." },
  { cat: 'Diritto Civile', d: "Quanto tempo ho per denunciare i vizi di un immobile acquistato?", r: "Il compratore deve denunciare i vizi entro 8 giorni dalla scoperta e può agire in giudizio entro 1 anno dalla consegna. Per vizi strutturali gravi degli immobili la garanzia è di 10 anni, mentre per la garanzia ordinaria il termine è di 1 anno dalla denuncia." },
  { cat: 'Diritto Civile', d: "Come funziona l'usucapione?", r: "L'usucapione permette di acquistare la proprietà di un bene mediante il possesso continuato e pacifico per un periodo stabilito dalla legge: 20 anni per i beni immobili (10 anni per il possesso in buona fede con titolo valido). Il possessore deve far accertare l'usucapione con sentenza del Tribunale." },
  { cat: 'Diritto Civile', d: "Come funziona il risarcimento danni da incidente stradale?", r: "Prima di agire in giudizio è necessario inviare richiesta risarcitoria all'assicurazione del responsabile (o al proprio CARD per i danni a cose). L'assicurazione ha 90 giorni per offrire un risarcimento (60 per i soli danni materiali). Se l'offerta è inadeguata, si può agire in giudizio. Una perizia medico-legale è fondamentale per quantificare il danno biologico." },
  { cat: 'Diritto Civile', d: "Cosa fare se ricevo un atto di pignoramento immobiliare?", r: "Ricevuto il pignoramento bisogna agire rapidamente: verificare la legittimità del titolo esecutivo; valutare se esistono motivi di opposizione (art. 615 c.p.c. per contestare il diritto del creditore; art. 617 c.p.c. per i vizi formali); valutare la possibilità di saldo e stralcio con il creditore." },

  // ── Diritto Tributario ────────────────────────────────────────────────────────
  { cat: 'Diritto Tributario', d: "Ho ricevuto una cartella esattoriale che non riconosco. Cosa faccio?", r: "Prima di tutto non ignorarla: i termini per opporsi decorrono dalla notifica. In generale si hanno 60 giorni per presentare ricorso alla Corte di Giustizia Tributaria (per vizi tributari) o opposizione al Giudice dell'Esecuzione (per vizi formali). È possibile richiedere anche la sospensione dell'esecutività." },
  { cat: 'Diritto Tributario', d: "Cosa si può fare se la cartella è prescritta?", r: "Se la cartella riguarda debiti prescritti, è possibile eccepire la prescrizione nel ricorso. I termini variano: IMU e tributi locali 5 anni; contributi previdenziali 5 anni; tributi erariali (IRPEF, IVA) 10 anni per l'iscrizione a ruolo. La prescrizione deve essere eccepita esplicitamente, non è rilevata d'ufficio." },
  { cat: 'Diritto Tributario', d: "Il Fisco può pignorare la casa principale?", r: "Il pignoramento della prima casa è vietato se il debitore vi risiede anagraficamente e il debito è inferiore a 120.000 euro (art. 76, comma 1, DPR 602/1973). Esistono eccezioni importanti, quindi è fondamentale verificare caso per caso." },
  { cat: 'Diritto Tributario', d: "Posso pagare i debiti tributari a rate?", r: "Sì. È possibile richiedere la rateizzazione delle cartelle esattoriali fino a 72 rate mensili per importi fino a 100.000 euro senza motivazione; per importi superiori è necessario documentare la difficoltà economica. Il mancato pagamento di 5 rate anche non consecutive fa decadere dalla rateizzazione." },
  { cat: 'Diritto Tributario', d: "Cos'è la rottamazione delle cartelle?", r: "La rottamazione è una definizione agevolata che consente di pagare il debito principale senza sanzioni e interessi di mora. Viene prevista periodicamente dal legislatore. Contattare lo studio per verificare quelle attualmente disponibili." },

  // ── Responsabilità Medica ─────────────────────────────────────────────────────
  { cat: 'Responsabilità Medica', d: "Cosa fare in caso di sospetto errore medico?", r: "Innanzitutto richiedere subito tutta la documentazione clinica (cartella clinica, referti, prescrizioni). Conservare ogni spesa sostenuta. Contattare uno studio legale specializzato prima di qualsiasi comunicazione con la struttura sanitaria. La Legge Gelli-Bianco (L. 24/2017) prevede l'ATP obbligatorio prima di avviare una causa." },
  { cat: 'Responsabilità Medica', d: "Entro quando posso chiedere il risarcimento per un errore medico?", r: "Il termine di prescrizione è di 5 anni dalla conoscenza del danno e della sua ricollegabilità alla condotta medica (non dall'intervento stesso). È fondamentale non aspettare: raccogliere la documentazione e consultare un legale il prima possibile." },
  { cat: 'Responsabilità Medica', d: "Cos'è l'ATP e perché è obbligatorio?", r: "L'Accertamento Tecnico Preventivo (ATP) è un procedimento cautelare davanti al Tribunale che permette di raccogliere prove tecniche prima del giudizio (perizia medico-legale). La Legge Gelli-Bianco lo rende obbligatorio come condizione di procedibilità dell'azione civile contro strutture sanitarie." },
  { cat: 'Responsabilità Medica', d: "Il medico e la struttura sono responsabili insieme?", r: "La struttura sanitaria risponde in via contrattuale (per il contratto di cura) e può essere chiamata a rispondere dei danni causati dai propri medici dipendenti. Il medico libero professionista risponde in via extracontrattuale. Dopo la Riforma Gelli-Bianco, il medico dipendente risponde solo per dolo o colpa grave." },
  { cat: 'Responsabilità Medica', d: "Come si quantifica il danno biologico da errore medico?", r: "Il danno biologico si quantifica con una perizia medico-legale che valuta la menomazione permanente (invalidità permanente) e temporanea. Si usa come riferimento la tabella delle Corti milanesi o la tabella unica nazionale per i micropermanenti. Al danno biologico si aggiunge il danno morale e patrimoniale." },

  // ── Diritto Penale ────────────────────────────────────────────────────────────
  { cat: 'Diritto Penale', d: "Cosa devo fare se ricevo un avviso di garanzia?", r: "L'avviso di garanzia non è un'imputazione: le indagini sono ancora in corso. Contattare immediatamente un legale. Non rendere dichiarazioni spontanee alle autorità senza la presenza dell'avvocato. Raccogliere tutta la documentazione utile per la propria difesa." },
  { cat: 'Diritto Penale', d: "Posso essere ascoltato senza avvocato?", r: "Sì, ma solo come persona informata sui fatti (testimone) e non come indagato. Se si è indagati, il diritto all'assistenza di un difensore è garantito dalla Costituzione (art. 24). Non si può essere costretti a rendere dichiarazioni auto-incriminanti (art. 63 c.p.p.)." },
  { cat: 'Diritto Penale', d: "Cos'è il patteggiamento e quando conviene?", r: "Il patteggiamento (applicazione della pena su richiesta) è un rito alternativo che permette di concordare una pena ridotta fino a un terzo rispetto a quella che si applicherebbe a seguito di condanna. Conviene quando gli elementi di prova sono gravi e il reato non è gravissimo. Non implica il riconoscimento della colpevolezza ai fini civili." },
  { cat: 'Diritto Penale', d: "Posso sporgere querela dopo molto tempo dall'accaduto?", r: "Per i reati procedibili a querela (insulti, percosse, minacce, truffa) il termine è generalmente di 3 mesi dalla scoperta del fatto. Per i reati perseguibili d'ufficio (rapina, lesioni gravi, violenza sessuale, omicidio) non ci sono termini per la denuncia ma esistono termini di prescrizione del reato." },

  // ── Previdenza e Pensioni ─────────────────────────────────────────────────────
  { cat: 'Previdenza e Pensioni', d: "Quando ho diritto alla NASpI?", r: "La NASpI spetta ai lavoratori dipendenti che perdono involontariamente il lavoro (licenziamento, fine contratto, dimissioni per giusta causa). Requisiti: almeno 13 settimane di contributi negli ultimi 4 anni e almeno 30 giorni lavorativi nell'ultimo anno. Durata: la metà delle settimane contributive degli ultimi 4 anni (max 24 mesi)." },
  { cat: 'Previdenza e Pensioni', d: "Posso contestare la valutazione dell'invalidità da parte della commissione medica?", r: "Sì. Il verbale della Commissione Medica Integrata ASL-INPS può essere impugnato: (1) con ricorso amministrativo all'INPS entro 60 giorni; (2) con azione giudiziaria al Tribunale del Lavoro previa ATP obbligatorio per le controversie in materia di invalidità civile (art. 445-bis c.p.c.)." },
  { cat: 'Previdenza e Pensioni', d: "Come funziona il riscatto della laurea ai fini pensionistici?", r: "Il riscatto della laurea (art. 2 D.Lgs. 184/1997) consente di accreditare ai fini pensionistici gli anni del corso legale di studio universitario. Il costo varia in base all'aliquota contributiva e al reddito. Esiste anche un riscatto agevolato (L. 232/2016) a costo ridotto. I costi sono deducibili fiscalmente." },

  // ── Costi e Preventivi ────────────────────────────────────────────────────────
  { cat: 'Costi e Preventivi', d: "Come vengono calcolati gli onorari dello studio?", r: "Gli onorari vengono determinati in base alla complessità della pratica, al tipo di incarico e alle tariffe forensi di riferimento (D.M. 55/2014 e successive modifiche). Per ogni incarico viene fornita preventivamente una informativa chiara e trasparente sui costi." },
  { cat: 'Costi e Preventivi', d: "È possibile avere un preventivo prima di conferire l'incarico?", r: "Sì. Lo studio fornisce sempre una informativa sui costi prima di accettare l'incarico, come previsto dall'art. 13 della Legge 247/2012 (Ordinamento Forense). Per pratiche complesse, il preventivo viene elaborato dopo un primo colloquio di valutazione del caso." },
]

export const FAQ_CATEGORIE = ['Tutte', ...Array.from(new Set(faqs.map(f => f.cat)))]
