export interface Testimonianza {
  i: string       // iniziali
  l: string       // localita
  m: string       // materia
  t: string       // testo
  a: string       // anno
  esito: string
}

export const testimonianze: Testimonianza[] = [
  { i: 'M.R.', l: 'Nocera Inferiore', m: 'Diritto di Famiglia',   t: "L'Avv. Cuomo ha gestito la mia separazione con grande professionalità e umanità. Mi ha sempre tenuto informato su ogni sviluppo, spiegandomi tutto con chiarezza. Grazie alla sua competenza ho ottenuto condizioni favorevoli per me e i miei figli.", a: '2025', esito: 'Accordo favorevole' },
  { i: 'G.F.', l: 'Pagani',           m: 'Diritto del Lavoro',    t: "Dopo un licenziamento illegittimo che mi sembrava impossibile da contestare, l'Avv. Cuomo ha analizzato il mio caso con precisione e ha ottenuto il risarcimento che meritavo. Studio serio, risposta sempre entro 24 ore.", a: '2025', esito: 'Risarcimento ottenuto' },
  { i: 'A.C.', l: 'Scafati',          m: 'Responsabilità Medica', t: "Ho affidato all'Avv. Cuomo un caso di malpractice medica dopo una brutta esperienza in ospedale. Ha seguito ogni dettaglio con estrema cura e alla fine abbiamo ottenuto un risarcimento giusto.", a: '2024', esito: 'Risarcimento ottenuto' },
  { i: 'R.T.', l: 'Angri',            m: 'Diritto Civile',        t: "Avevo una disputa condominiale che si trascinava da anni. L'Avv. Cuomo ha risolto la questione in pochi mesi con risultato eccellente e onorari trasparenti.", a: '2024', esito: 'Controversia risolta' },
  { i: 'L.M.', l: "Cava de' Tirreni", m: 'Diritto Tributario',    t: "Mi è arrivata una cartella esattoriale enorme che non riconoscevo. L'Avv. Cuomo ha presentato ricorso con argomenti solidi. La cartella è stata annullata. Preparazione eccezionale e massima disponibilità.", a: '2025', esito: 'Cartella annullata' },
  { i: 'S.D.', l: 'Nocera Inferiore', m: 'Recupero Crediti',      t: "Avevo un credito importante da recuperare da un cliente moroso. Lo studio ha gestito tutto in modo rapido ed efficace, dal decreto ingiuntivo all'esecuzione.", a: '2024', esito: 'Credito recuperato' },
  { i: 'C.V.', l: 'Salerno',          m: 'Diritto di Famiglia',   t: "Divorzio difficile con questioni patrimoniali complesse. L'Avv. Cuomo ha dimostrato una preparazione eccellente e una capacità negoziale rara. Abbiamo raggiunto un accordo in tempi ragionevoli.", a: '2025', esito: 'Accordo raggiunto' },
  { i: 'P.E.', l: 'Caserta',          m: 'Diritto del Lavoro',    t: "Sono stata vittima di mobbing sul lavoro per due anni. L'Avv. Cuomo ha costruito un dossier rigoroso e portato il caso in tribunale con risultati eccellenti. Finalmente giustizia.", a: '2024', esito: 'Vittoria in giudizio' },
  { i: 'F.N.', l: 'Napoli',           m: 'Diritto Civile',        t: "Ho acquistato un immobile con gravi vizi nascosti. L'Avv. Cuomo ha gestito la causa per risoluzione del contratto con grande competenza tecnica.", a: '2025', esito: 'Contratto risolto' },
  { i: 'D.L.', l: 'Avellino',         m: 'Diritto Tributario',    t: "Controversia con l'Agenzia delle Entrate su imposte che non dovevo. L'Avv. Cuomo ha vinto in Commissione Tributaria al primo grado. Studio serio e professionale al 100%.", a: '2024', esito: 'Vittoria CGT' },
  { i: 'M.S.', l: 'Sarno',            m: 'Diritto di Famiglia',   t: "Caso di affidamento minorile molto delicato. L'Avv. Cuomo ha dimostrato grande sensibilità oltre che competenza giuridica. Ho ottenuto l'affidamento condiviso nelle condizioni che auspicavo.", a: '2025', esito: 'Affidamento ottenuto' },
  { i: 'T.B.', l: 'Torre Annunziata', m: 'Diritto Penale',        t: "Accusato ingiustamente in un procedimento penale, ero disperato. L'Avv. Cuomo mi ha assistito con dedizione dalla fase delle indagini fino all'assoluzione in dibattimento.", a: '2024', esito: 'Assoluzione' },
  { i: 'E.R.', l: 'Castellammare',    m: 'Responsabilità Medica', t: "Mio padre ha subito danni gravi in seguito a un'operazione sbagliata. L'Avv. Cuomo ha guidato tutta la procedura con competenza e ci ha ottenuto un risarcimento proporzionato.", a: '2025', esito: 'Risarcimento ottenuto' },
  { i: 'V.G.', l: 'Nocera Inferiore', m: 'Diritto del Lavoro',    t: "Dipendente da 15 anni, licenziata senza giusta causa a 55 anni. L'Avv. Cuomo ha impugnato il licenziamento e ottenuto il reintegro oltre a tutte le mensilità arretrate.", a: '2024', esito: 'Reintegro + arretrati' },
  { i: 'O.P.', l: 'Pompei',           m: 'Diritto Civile',        t: "Controversia successoria tra fratelli su un immobile di famiglia. L'Avv. Cuomo ha mediato con intelligenza e trovato una soluzione extragiudiziale soddisfacente per tutti.", a: '2025', esito: 'Accordo extragiudiziale' },
  { i: 'B.C.', l: 'Nola',             m: 'Recupero Crediti',      t: "Da imprenditore avevo diversi crediti inesigibili. Lo studio ha strutturato un'azione legale coordinata e ho recuperato la maggior parte dei crediti in pochi mesi.", a: '2024', esito: 'Recupero pluricrediti' },
  { i: 'I.M.', l: 'Eboli',            m: 'Diritto di Famiglia',   t: "Negoziazione assistita per la separazione: in meno di due mesi abbiamo chiuso tutto. L'Avv. Cuomo ha reso un momento difficile molto meno traumatico del previsto.", a: '2025', esito: 'Chiuso in 2 mesi' },
  { i: 'N.A.', l: 'Napoli',           m: 'Diritto Tributario',    t: "Contestazione di avviso di accertamento IRPEF per somme ingenti. L'Avv. Cuomo ha costruito una difesa tecnica eccellente. Accolto il ricorso in primo grado.", a: '2024', esito: 'Ricorso accolto' },
  { i: 'Q.D.', l: 'Pagani',           m: 'Diritto del Lavoro',    t: "Lavoravo in nero da tre anni. L'Avv. Cuomo ha fatto valere i miei diritti previdenziali e ottenuto il riconoscimento del rapporto di lavoro con tutti i versamenti contributivi.", a: '2025', esito: 'Diritti riconosciuti' },
  { i: 'H.K.', l: 'Salerno',          m: 'Diritto Civile',        t: "Sono straniero e temevo di non capire nulla del sistema legale italiano. L'Avv. Cuomo mi ha assistito con pazienza e chiarezza in ogni fase della controversia. Risultato ottimo.", a: '2024', esito: 'Controversia risolta' },
  { i: 'U.F.', l: 'Scafati',          m: 'Responsabilità Medica', t: "Mia moglie ha subito danni permanenti per un errore anestesiologico. L'Avv. Cuomo ha coordinato la consulenza medico-legale e la strategia processuale con precisione assoluta.", a: '2025', esito: 'Risarcimento ottenuto' },
  { i: 'W.Z.', l: 'Angri',            m: 'Diritto di Famiglia',   t: "Revisione dell'assegno di mantenimento per cambio delle circostanze. L'Avv. Cuomo ha presentato un ricorso ben documentato e ha ottenuto la riduzione che chiedevo.", a: '2024', esito: 'Riduzione ottenuta' },
  { i: 'X.B.', l: 'Nocera Superiore', m: 'Diritto Civile',        t: "Sinistro stradale con danni fisici rilevanti. L'assicurazione mi offriva un risarcimento ridicolo. L'Avv. Cuomo ha quantificato correttamente il danno e ottenuto tre volte quanto mi offrivano.", a: '2025', esito: 'Risarcimento triplicato' },
  { i: 'Y.T.', l: 'Battipaglia',      m: 'Diritto del Lavoro',    t: "Causa per mancato pagamento del TFR e di tre mensilità. Recuperato tutto con gli interessi in soli sei mesi. Studio affidabile e consigliatissimo.", a: '2024', esito: 'TFR + arretrati' },
  { i: 'Z.R.', l: 'Nocera Inferiore', m: 'Diritto Tributario',    t: "Controversia IVA complessa con la Guardia di Finanza. L'Avv. Cuomo ha studiato ogni documento con meticolosità e la vertenza si è chiusa con un accordo favorevole.", a: '2025', esito: 'Accordo favorevole' },
  { i: 'A.B.', l: 'Mercato S.S.',     m: 'Diritto Civile',        t: "Ristrutturazione eseguita male dall'appaltatore. L'Avv. Cuomo ha ottenuto il risarcimento delle spese di riparazione e dei danni consequenziali. Molto soddisfatto.", a: '2024', esito: 'Risarcimento danni' },
  { i: 'C.F.', l: 'Salerno',          m: 'Recupero Crediti',      t: "Professionista con un credito insoluto verso un'azienda in difficoltà. Il decreto ingiuntivo è stato ottenuto in meno di un mese e il pignoramento ha funzionato perfettamente.", a: '2025', esito: 'Credito recuperato' },
  { i: 'D.G.', l: 'Potenza',          m: 'Diritto di Famiglia',   t: "Procedimento per sottrazione internazionale di minore. Caso delicatissimo che richiedeva competenze specialistiche. L'Avv. Cuomo ha gestito ogni aspetto con assoluta professionalità.", a: '2024', esito: 'Minore rientrato' },
  { i: 'E.M.', l: 'Napoli',           m: 'Responsabilità Medica', t: "Intervento chirurgico con complicazioni evitabili. Dopo un lungo percorso, l'Avv. Cuomo ha ottenuto un risarcimento giusto sia per il danno biologico che per quello patrimoniale.", a: '2025', esito: 'Doppio risarcimento' },
  { i: 'F.P.', l: 'Avellino',         m: 'Diritto del Lavoro',    t: "Dipendente pubblico sanzionato disciplinarmente in modo ingiusto. L'Avv. Cuomo ha impugnato il provvedimento davanti al TAR e ha ottenuto l'annullamento della sanzione.", a: '2024', esito: 'Sanzione annullata' },
  { i: 'G.R.', l: 'Nocera Inferiore', m: 'Diritto Civile',        t: "Lite condominiale su una servitù di passaggio contestata. L'Avv. Cuomo ha risolto la questione richiamando una sentenza della Cassazione perfettamente pertinente. Brillante.", a: '2025', esito: 'Sentenza Cass. citata' },
  { i: 'H.S.', l: "Cava de' Tirreni", m: 'Diritto Tributario',    t: "Accertamento sintetico sul reddito (redditometro). L'Avv. Cuomo ha demolito le presunzioni dell'ufficio una per una. Accertamento annullato nella sua totalità.", a: '2024', esito: 'Accertamento annullato' },
  { i: 'I.V.', l: 'Pagani',           m: 'Diritto di Famiglia',   t: "Separazione con tre figli minori e questioni patrimoniali complesse. L'Avv. Cuomo ha tutelato me e soprattutto i miei figli con attenzione e competenza insuperabili.", a: '2025', esito: 'Tutela figli' },
  { i: 'L.C.', l: 'Caserta',          m: 'Recupero Crediti',      t: "Azienda con crediti verso clienti inadempienti. Lo studio ha gestito cinque decreti ingiuntivi contemporaneamente in modo impeccabile e professionale.", a: '2024', esito: '5 DI ottenuti' },
  { i: 'M.D.', l: 'Napoli',           m: 'Diritto Penale',        t: "Indagato per un reato che non avevo commesso. L'Avv. Cuomo ha presentato una memoria difensiva efficacissima al PM e il procedimento si è chiuso con l'archiviazione.", a: '2025', esito: 'Archiviazione' },
  { i: 'N.E.', l: 'Torre del Greco',  m: 'Diritto del Lavoro',    t: "Accordo sindacale firmato sotto pressione. L'Avv. Cuomo ha impugnato la transazione per vizi del consenso e abbiamo ottenuto una transazione molto più favorevole.", a: '2024', esito: 'Transazione migliorata' },
  { i: 'O.F.', l: 'Nocera Inferiore', m: 'Responsabilità Medica', t: "Ritardo diagnostico oncologico con conseguenze gravi per mio padre. L'Avv. Cuomo ci ha sostenuti in ogni momento, anche umanamente. Un avvocato con valori veri.", a: '2025', esito: 'Risarcimento + supporto' },
  { i: 'P.G.', l: 'Scafati',          m: 'Diritto Civile',        t: "Compravendita immobiliare con vizi occulti. L'Avv. Cuomo ha ottenuto la riduzione del prezzo e il rimborso delle spese di bonifica. Ineccepibile per competenza e serietà.", a: '2024', esito: 'Riduzione prezzo' },
  { i: 'R.I.', l: 'Angri',            m: 'Diritto di Famiglia',   t: "Modifica delle condizioni di separazione dopo anni. L'Avv. Cuomo ha gestito il ricorso con tempestività e ha ottenuto il riconoscimento dell'assegno perequativo che spettava.", a: '2024', esito: 'Assegno riconosciuto' },
  { i: 'S.L.', l: 'Napoli',           m: 'Diritto del Lavoro',    t: "Discriminazione sul lavoro per ragioni sindacali. L'Avv. Cuomo ha avviato il procedimento d'urgenza ex art. 28 e ha ottenuto la rimozione del comportamento antisindacale.", a: '2025', esito: 'Comportamento rimosso' },
  { i: 'T.M.', l: 'Nocera Superiore', m: 'Recupero Crediti',      t: "Socio di una SRL che mi doveva una somma rilevante. Grazie all'Avv. Cuomo abbiamo ottenuto il pignoramento del conto aziendale e recuperato tutto il dovuto.", a: '2024', esito: 'Pignoramento ok' },
  { i: 'U.N.', l: 'Battipaglia',      m: 'Diritto Penale',        t: "Denuncia per guida in stato di ebbrezza con incidente. L'Avv. Cuomo ha gestito la fase dibattimentale con grande abilità e ho patteggiato una pena sospesa senza conseguenze sul lavoro.", a: '2025', esito: 'Pena sospesa' },
  { i: 'V.O.', l: 'Nocera Inferiore', m: 'Diritto Civile',        t: "Contratto di locazione commerciale con clausole capestro. L'Avv. Cuomo ha negoziato la risoluzione anticipata senza penali eccessive. Studio indispensabile per qualsiasi questione legale.", a: '2024', esito: 'Risoluzione senza penali' },
  { i: 'W.P.', l: 'Salerno',          m: 'Responsabilità Medica', t: "Complicanze da parto: l'Avv. Cuomo ha coordinato una perizia medico-legale accuratissima e condotto la negoziazione con la struttura sanitaria fino a un accordo soddisfacente.", a: '2025', esito: 'Accordo con struttura' },
  { i: 'Y.R.', l: 'Pagani',           m: 'Diritto di Famiglia',   t: "Affidamento esclusivo per situazione di pericolo per il minore. L'Avv. Cuomo ha agito con assoluta urgenza ottenendo il provvedimento cautelare in pochissimi giorni.", a: '2025', esito: 'Cautelare urgente' },
  { i: 'Z.S.', l: 'Nocera Inferiore', m: 'Diritto del Lavoro',    t: "Infortunio sul lavoro non denunciato dall'azienda. L'Avv. Cuomo ha attivato tutte le procedure INAIL e ottenuto il riconoscimento della rendita da inabilità permanente parziale.", a: '2024', esito: 'Rendita INAIL' },
  { i: 'A.T.', l: "Cava de' Tirreni", m: 'Diritto Civile',        t: "Confine tra fondi oggetto di disputa da decenni tra due famiglie. L'Avv. Cuomo ha risolto la controversia con un accordo transattivo intelligente che ha soddisfatto entrambe le parti.", a: '2025', esito: 'Accordo transattivo' },
  { i: 'B.U.', l: 'Salerno',          m: 'Recupero Crediti',      t: "Professionista sanitario con crediti verso pazienti insolventi. Lo studio ha predisposto una strategia di recupero efficace rispettando la deontologia del settore. Consiglio vivamente.", a: '2025', esito: 'Recupero etico' },
]

export const MATERIE = ['Tutte', ...Array.from(new Set(testimonianze.map(t => t.m)))]
